### PR TITLE
update with fresh mainline build

### PR DESCRIPTION
**Pull request by bkleiner**

### CODE REVIEW

**Review by amoxu — COMMENTED** [review]
Was the linux & mac binaries built with static linking libusb & libhidapi & libftdi?

**Comment by amoxu** [comment]
And linux binary size increased too much, was it stripped?

**Comment by bkleiner** [comment]
uhmm, i was just about to push a stripped version :D

**Comment by amoxu** [comment]
Nevermind, your can make a pull request at any time.

**Pull request merged**
